name: Build

on:
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'extras/images/**'

env:
  PACKAGE_NAME: godotx_firebase

jobs:
  build:
    name: Build Extension
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "17"

      - name: Install Dependencies
        run: |
          brew install xcodegen scons
          sudo gem install cocoapods

      - name: Setup Godot
        run: make setup-godot

      - name: Build Godot headers
        run: make build-godot-headers

      - name: Setup Firebase
        run: make setup-firebase

      - name: Unsign Firebase
        run: make unsign-firebase

      - name: Build Android
        run: make build-android

      - name: Build iOS
        run: make build-apple

      - name: Create package
        run: make package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: ${{ env.PACKAGE_NAME }}.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.PACKAGE_NAME }}.zip